In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv


In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [3]:
train_df = pd.read_csv("/kaggle/input/digit-recognizer/train.csv")
test_df = pd.read_csv("/kaggle/input/digit-recognizer/test.csv")
train_df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
print(train_df.shape)
print(test_df.shape)

(42000, 785)
(28000, 784)


In [5]:
train_x = train_df.drop(["label"],axis=1).astype("int32")
train_y = train_df["label"].astype("float32")
test_x = test_df.astype("float32")
train_x.shape, train_y.shape, test_x.shape

((42000, 784), (42000,), (28000, 784))

In [6]:
train_x.describe()

pixel0   pixel1   pixel2   pixel3   pixel4   pixel5   pixel6   pixel7  \
count  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel8   pixel9  ...      pixel774      pixel775      pixel776  \
count  42000.0  42000.0  ...  42000.000000  42000.000000  42000.000000   
mean       0.0      0.0  ...      0.219286      0.117095      0.059024   
std        0.0      0.0  ...      6.312890      4.633819      3.274488   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...    254.000000    254.000000    253.000000   

          pixel777      pixel778      pixel779  pixel780  pixel781  pixel782  \
count  42000.00000  42000.000000  42000.000000   42000.0   42000.0   42000.0   
mean       0.02019      0.017238      0.002857       0.0       0.0       0.0   
std        1.75987      1.894498      0.414264       0.0       0.0       0.0   
min        0.00000      0.000000      0.000000       0.0       0.0       0.0   
25%        0.00000      0.000000      0.000000       0.0       0.0       0.0   
50%        0.00000      0.000000      0.000000       0.0       0.0       0.0   
75%        0.00000      0.000000      0.000000       0.0       0.0       0.0   
max      253.00000    254.000000     62.000000       0.0       0.0       0.0   

       pixel783  
count   42000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 784 columns]

In [7]:
train_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 784 entries, pixel0 to pixel783
dtypes: int32(784)
memory usage: 125.6 MB


In [8]:
train_x = train_x.values.reshape(-1,28,28,1)
train_x = train_x/255.0
test_x = test_x.values.reshape(-1,28,28,1)
test_x = test_x/255.0
train_x.shape, test_x.shape

((42000, 28, 28, 1), (28000, 28, 28, 1))

In [9]:
# One hot encoding
train_y = tf.keras.utils.to_categorical(train_y,10)
train_y.shape

(42000, 10)

In [10]:
train_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [11]:
train_df["label"].head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [12]:
print(train_y[0:5,:])

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
# Defining the model
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32,(3,3),activation = "relu", input_shape=(28,28,1)),
    tf.keras.layers.Conv2D(32,(3,3),activation="relu"),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3),activation="relu",padding = "Same"),
    tf.keras.layers.Conv2D(64,(3,3),activation ="relu",padding = "Same"),
    tf.keras.layers.MaxPooling2D(pool_size =(2,2), strides=(2,2)),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Conv2D(64,(3,3),activation ="relu",padding = "Same"),
    tf.keras.layers.Conv2D(64,(3,3),activation ="relu",padding = "Same"),
    tf.keras.layers.MaxPooling2D(pool_size =(2,2), strides=(2,2)),
    tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dropout(0.50),
    tf.keras.layers.Dense(10, activation="softmax"),
])

model.summary()

/opt/conda/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 24, 24, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 12, 12, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 12, 12, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 12, 12, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 6, 6, 64)       │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 6, 6, 64)       │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 3, 3, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 3, 3, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 576)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 256)            │       147,712 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 256)            │        65,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 354,922 (1.35 MB)

 Trainable params: 354,922 (1.35 MB)

 Non-trainable params: 0 (0.00 B)

In [14]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy') > 0.999):
            print("\nReached 99.9% accuracy, So here training Hold!!!")
            self.model.stop_training = True

callbacks = myCallback()

In [15]:
Optimizer = tf.keras.optimizers.Adam(
    learning_rate = 0.0005,
    beta_1 = 0.9,
    beta_2 = 0.999,
    epsilon = 1e-07,
    name='Adam'
)
model.compile(optimizer = Optimizer, loss = "categorical_crossentropy",metrics=["accuracy"])
model.fit(train_x,train_y,batch_size =50, epochs = 20, callbacks= [callbacks])

Epoch 1/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 69s 78ms/step - accuracy: 0.7228 - loss: 0.7894
Epoch 2/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 82s 78ms/step - accuracy: 0.9729 - loss: 0.0925
Epoch 3/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 66s 78ms/step - accuracy: 0.9823 - loss: 0.0621
Epoch 4/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 82s 78ms/step - accuracy: 0.9860 - loss: 0.0504
Epoch 5/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 80s 76ms/step - accuracy: 0.9880 - loss: 0.0398
Epoch 6/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 64s 76ms/step - accuracy: 0.9890 - loss: 0.0358
Epoch 7/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 81s 75ms/step - accuracy: 0.9912 - loss: 0.0271
Epoch 8/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 82s 76ms/step - accuracy: 0.9927 - loss: 0.0268
Epoch 9/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 64s 76ms/step - accuracy: 0.9927 - loss: 0.0248
Epoch 10/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 82s 76ms/step - accuracy: 0.9927 - loss: 0.0214
Epoch 11/20
840/840 ━━━━━━━━━━━━━━━━━━━━ 63s 76ms/step - accuracy: 0.9943 - loss: 0.0196
Epoch 12/20
840/840 ━━━━━━━━━━

In [16]:
results = model.predict(test_x)
results = np.argmax(results,axis=1)
results = pd.Series(results,name="Label")

875/875 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step


In [17]:
sub_df = pd.read_csv("/kaggle/input/digit-recognizer/sample_submission.csv")
sub_df.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [18]:
x_index  = sub_df["ImageId"]

In [19]:
submission = pd.DataFrame({
    'ImageId': x_index,
    'Label': results
})
submission.to_csv("Digit_Submission.csv",index=False)

In [20]:
submission.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      0
4        5      3